### ISSUE TITLE
[Request] Atom Support

### ISSUE THREAD

**Issue by Braunson** [cybercog/laravel-whoops-editor#3]
Any idea if we can support Atom, I took a look but didn't find any `atom://` helper available

**Comment by antonkomarev** [comment]
@Braunson as far as I know for MacOS it is `atom://`. I haven't tried to use atom scheme on Linux and Windows. Could you test it or I should do it later?

**Comment by Braunson** [comment]
Looks like Atom supports the URI handler `atom://` in Windows, going to try it next.

Edit: I tried `'atom' => 'atom://open?url=%file&line=%line',` without success,.

I guess it could work with this package installed https://github.com/WizardOfOgz/atom-handler and using `atm://`. I just wish there was native Atom support.

There's also a linux package to make this work also https://github.com/eclemens/atom-url-handler

**Comment by Braunson** [comment]
Looks like this was a feature request here https://github.com/atom/atom/issues/2037 and https://github.com/atom/atom/pull/11399

Hopefully it'll be released soon!

**Comment by antonkomarev** [comment]
Thank you for research @Braunson!

By the way, this one should work with handlers which you've provided above.
```php
'atom' => 'atm://open?url=file://%file&line=%line',
```
Or without `file://`:
```php
'atom' => 'atm://open?url=%file&line=%line',
```

**Comment by antonkomarev** [comment]
Additionally I've added [table with protocol handlers](https://github.com/cybercog/laravel-whoops-editor#protocol-handlers) to README usage section.
