### ISSUE TITLE
[Request] Variable project path

### ISSUE THREAD

**Issue by ghost** [cybercog/laravel-whoops-editor#4]
Thanks for setting up the Linux support, I appreciate it.

I am having trouble however, opening phpstorm since the filename it tries to open doesnt exist on my machine. I use a Docker container for my development environment and the "open" url refers to the virtual filesystem, not to the one on my host machine.

Is there a way of setting the project path so I can map it to my host machine?

Thanks!

**Comment by antonkomarev** [comment]
Hello @megaxlr!

You could [publish config file](https://github.com/cybercog/laravel-whoops-editor#configuration) and change `local-projects-path` & `homestead-projects-path` to fit your requirements.

Its not only for homestead for real. It just replaces `homestead-project-path` value in debug file opener with `local-projects-path` value.

For example, by default it gets path like:
`/home/vagrant/projects/anything-here/anyfile.php`
And replaces it with:
`~/projects/anything-here/anyfile.php`

**Comment by ghost** [comment]
Oops, completely overlooked that. 

Thanks!

**Comment by antonkomarev** [comment]
Thats OK. Glad you solved the issue. This feature should be described in README.
